language: python
python:
  - "3.8"
branches:
  only:
  - develop
  - master
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install
script:
  - poetry run tox
after_success:
  - codecov
notifications:
  email: false
