[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pyrdf2vec"
version = "0.0.5"
description = "Python implementation and extension of RDF2Vec"
license = "Ghent University and IMEC vzw"
authors = [
    "Gilles Vandewiele <gilles.vandewiele@ugent.be>",
    "Bram Steenwinckel <bram.steenwinckel@ugent.be>",
    "Michael Weyns <michael.weyns@ugent.be>"
]
maintainers = ["Gilles Vandewiele <gilles.vandewiele@ugent.be>"]
readme = "README.md"
repository = "https://github.com/IBCNServices/pyRDF2Vec"
documentation = "https://pyrdf2vec.readthedocs.io/en/latest/"
keywords = ["embeddings", "knowledge-graph", "rdf2vec", "word2vec"]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Build Tools"
]
include = [
    "LICENSE",
    "README.md",
]

[tool.poetry.dependencies]
attrs = "^20.1.0"
gensim = "^3.8.3"
matplotlib = "^3.3.1"
networkx = "^2.5"
numpy = "^1.19.1"
pandas = "^1.1.1"
python = "^3.8"
python-louvain = "^0.14"
rdflib = "^5.0.0"
scikit-learn = "^0.23.2"
tqdm = "^4.48.2"
tomlkit = "^0.7.0"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^20.8b1"
codecov = "^2.1.9"
doc8 = "^0.8.1"
flake8 = "^3.8.3"
isort = "^5.4.2"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
sphinx = "^3.2.1"
sphinx-rtd-theme = "^0.5.0"
sphinxcontrib-napoleon = "^0.7"
tox = "^3.19.0"
yamllint = "^1.24.2"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon", "tomlkit"]
lint = ["black", "doc8", "flake8", "isort", "yamllint"]
tests = ["codecov", "pytest", "pytest-cov"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/IBCNServices/pyRDF2Vec/issues"

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.tox
  | _build
  | build
  | dist
  | env
)/
'''

[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    docs
    py38
    lint
    tests
isolated_build = True

[testenv:docs]
description = Builds documentation (HTML) with Sphinx.
deps =
    sphinx
    sphinx-rtd-theme
    sphinxcontrib-napoleon
    tomlkit
commands =
    sphinx-apidoc -f -o docs pyrdf2vec
    sphinx-build -n -T docs docs/{envtmpdir}/html
    python -m doctest README.md

[testenv:lint]
description = Checks the code style.
deps = pre-commit
skip_install = true
commands = pre-commit run --all-files

[testenv:tests]
description = Runs unit tests and performs coverage.
deps =
    codecov
    pytest
    pytest-cov
commands = pytest --cov=pyrdf2vec tests
"""
